# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

trailingComma: 'es5'
printWidth: 90
semi: true
singleQuote: true
bracketSameLine: true
singleAttributePerLine: false
useTabs: false
tabWidth: 2
